{% set version = "0.9.5" %}

package:
  name: pykalman
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykalman/pykalman-{{ version }}.tar.gz
  sha256: 816af47720d924a4c6016fa74b9e2c8c21165a08d91693c322a1741e8e07fb38

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - pykalman
    - pykalman.datasets
    - pykalman.sqrt
    - pykalman.sqrt.tests
    - pykalman.tests

about:
  home: http://pykalman.github.io
  license: BSD 3-Clause
  summary: 'An implementation of the Kalman Filter, Kalman Smoother, and EM algorithm in Python'

extra:
  recipe-maintainers:
    - pmlandwehr
